### PR TITLE
Added Indonesian Translation

### PR DESCRIPTION
**Pull request by the7thNightmare**
Thanks for making this game. This is the translation of Lona to Indonesian Language.

### CODE REVIEW

**Comment by lufte** [comment]
Thank you! Since you're here, I plan to add a new link to a post I wrote in my blog detailing how I wrote this game. That text will also need to be translated, so maybe I can request you the Indonesian version now. The text will be "Read about how Lona was written in my blog: https://lufte.net/en/post/lona-chronicles/". No need to add it to the locales.ini file yet, just leave a comment with it.

**Comment by the7thNightmare** [comment]
I don't know where to put that text is, sorry. The translated text is "Baca bagaimana Lona dibuat di blog saya: https://lufte.net/en/post/lona-chronicles/." Language identifier for Indonesian is `id` and `in`, so its best to put this on that two. Thanks.

**Comment by lufte** [comment]
Thanks! No need to put it anywhere yet, I'll use it afterwards when I add that new text.

Regarding your changes, I don't find `in` as a language code for Indonesia in [Wikipedia](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes). [id](https://www.loc.gov/standards/iso639-2/php/langcodes_name.php?iso_639_1=id) is listed as the only code, and [in](https://www.loc.gov/standards/iso639-2/php/langcodes_name.php?iso_639_1=in) doesn't exist. Where did you get that information?

**Comment by the7thNightmare** [comment]
In the notes on Indonesian Language, the old language identifier. I also translate other apps, and it didn't recognize automatically for `id` but recognize for `in` although I use Android 8, [references](https://github.com/Breta01/docus/pull/22).

**Review by lufte — APPROVED** [review]

**Pull request merged**
